# Generated by Django 4.0.3 on 2022-04-26 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 7, 13, 825289), verbose_name='Дата регистрации')),
                ('user', models.CharField(default='пользователь', max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(default='телефон', max_length=25, verbose_name='Телефон')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('profile', models.CharField(max_length=100, verbose_name='Направление')),
                ('edu_form', models.CharField(max_length=20, verbose_name='Форма обучения')),
                ('place', models.CharField(max_length=20, verbose_name='Форма оплаты')),
                ('employment', models.CharField(max_length=20, verbose_name='Трудоустройство')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': "Программа 'Выбор профессии'",
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='InteresCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='InteresUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 7, 13, 826289), verbose_name='Дата регистрации')),
                ('user', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interescategorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пользовател',
                'verbose_name_plural': 'Пользователь',
                'ordering': ('-date',),
            },
        ),
    ]
