# Generated by Django 4.0.3 on 2022-05-24 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'активный'), ('passive', 'не активный')], default='active', max_length=15, verbose_name='Статус')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 19, 58, 666444), verbose_name='Дата регистрации')),
                ('user', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('profile', models.CharField(max_length=100, verbose_name='Направление')),
                ('edu_form', models.CharField(max_length=20, verbose_name='Форма обучения')),
                ('place', models.CharField(max_length=20, verbose_name='Форма оплаты')),
                ('employment', models.CharField(max_length=20, verbose_name='Трудоустройство')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': "Программа 'Выбор профессии'",
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='InteresCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.FileField(upload_to='main/partners/logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/ответ',
                'verbose_name_plural': 'Вопросы/ответы',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='InteresUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'активный'), ('passive', 'не активный')], default='active', max_length=15, verbose_name='Статус')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 19, 58, 667445), verbose_name='Дата регистрации')),
                ('user', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interescategorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-date',),
            },
        ),
    ]
