# Generated by Django 4.0.3 on 2022-04-26 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_choiceprogram_date_alter_interesusermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceprogram',
            name='status',
            field=models.CharField(choices=[('active', 'активный'), ('passive', 'не активный')], default='active', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='interesusermodel',
            name='status',
            field=models.CharField(choices=[('active', 'активный'), ('passive', 'не активный')], default='active', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 11, 57, 431366), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 11, 57, 432366), verbose_name='Дата регистрации'),
        ),
    ]
