# Generated by Django 4.0.3 on 2022-04-26 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_choiceprogram_status_interesusermodel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesusermodel',
            options={'ordering': ('-date',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 13, 7, 393779), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 2, 13, 7, 394781), verbose_name='Дата регистрации'),
        ),
    ]
