# Generated by Django 4.0.3 on 2022-04-30 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_interesusermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceprogram',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=50, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 58, 31, 791438), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 58, 31, 791438), verbose_name='Дата регистрации'),
        ),
    ]
