# Generated by Django 4.0.3 on 2022-05-01 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_choiceprogram_email_alter_choiceprogram_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 3, 51, 20, 447367), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='email',
            field=models.CharField(max_length=50, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 3, 51, 20, 449366), verbose_name='Дата регистрации'),
        ),
    ]
