# Generated by Django 4.0.3 on 2022-05-24 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_choiceprogram_date_alter_interesusermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesusermodel',
            name='email',
            field=models.EmailField(default='None@gmail.com', max_length=50, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 27, 17, 756022), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 1, 27, 17, 758024), verbose_name='Дата регистрации'),
        ),
    ]
