# Generated by Django 4.0.3 on 2022-05-11 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partnersmodel_alter_choiceprogram_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 9, 4, 49, 185390), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 9, 4, 49, 185390), verbose_name='Дата регистрации'),
        ),
    ]
