# Generated by Django 4.0.3 on 2022-05-24 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_interesusermodel_email_alter_choiceprogram_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 2, 8, 57, 165715), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='choiceprogram',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 2, 8, 57, 165715), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=50, verbose_name='e-mail'),
        ),
    ]
