# Generated by Django 4.0.3 on 2022-05-25 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_choiceprogram_date_alter_choiceprogram_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 9, 47, 6, 959836), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 9, 47, 6, 959836), verbose_name='Дата регистрации'),
        ),
    ]
