# Generated by Django 4.0.3 on 2022-05-11 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_choiceprogram_date_alter_interesusermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceprogram',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 14, 21, 23, 781910), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='interesusermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 14, 21, 23, 782909), verbose_name='Дата регистрации'),
        ),
    ]
