# Generated by Django 4.0.3 on 2022-04-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('numeric', models.CharField(blank=True, max_length=250, verbose_name='Число')),
                ('image', models.FileField(blank=True, null=True, upload_to='faculty/images/icons/detail', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='faculty/images/documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='ссылка')),
                ('detail', models.ManyToManyField(related_name='detail_education', to='faculty.detailmodel', verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EduFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, verbose_name='Ссылка')),
                ('status', models.CharField(choices=[('middle', 'среднее'), ('post', 'высшее')], default='post', max_length=20, verbose_name='Образование')),
                ('logo', models.FileField(blank=True, upload_to='faculty/images/icons/faculty', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.CharField(max_length=250, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SpecialAbilitiesDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Деталь специальных возможностей',
                'verbose_name_plural': 'Детали специальных возможностей',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(upload_to='faculty/images/teachers', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpecialAbilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('details', models.ManyToManyField(blank=True, related_name='abilities_detail', to='faculty.specialabilitiesdetailmodel', verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Специальная возможность',
                'verbose_name_plural': 'Специальные возможности',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('logo', models.FileField(blank=True, upload_to='faculty/images/logo', verbose_name='Логотип')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('work_places', models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Места работы')),
                ('suitable', models.TextField(blank=True, help_text='Поле может быть пустым', null=True, verbose_name='Подходит для кого')),
                ('description', models.TextField(verbose_name='Описание')),
                ('courses', models.ManyToManyField(related_name='courses', to='faculty.coursemodel', verbose_name='Курсы')),
                ('documents', models.ManyToManyField(related_name='documents', to='faculty.documentmodel', verbose_name='Документы')),
                ('edu_form', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eduform', to='faculty.eduformmodel', verbose_name='Форма обучения')),
                ('education', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='faculty.educationmodel', verbose_name='Образование')),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='faculty.facultymodel', verbose_name='Факультет')),
                ('professions', models.ManyToManyField(related_name='professions', to='faculty.professionmodel', verbose_name='Професии')),
                ('skills', models.ManyToManyField(related_name='skills', to='faculty.skillmodel', verbose_name='Навыки')),
                ('teachers', models.ManyToManyField(related_name='teachers', to='faculty.teachermodel', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='special_abilities',
            field=models.ManyToManyField(related_name='education_specialabilities', to='faculty.specialabilitiesmodel', verbose_name='Специальные вопросы'),
        ),
    ]
