# Generated by Django 4.0.3 on 2022-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='rank',
            field=models.CharField(choices=[('no', 'Отсутствует'), ('professior', 'Почетные профессора'), ('doctor', 'Почетные доктора')], default='no', max_length=50, verbose_name='Статус'),
        ),
    ]
