# Generated by Django 4.0.3 on 2022-05-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_teachermodel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='rank',
            field=models.CharField(choices=[('no', 'Отсутствует'), ('professor', 'Почетный профессор'), ('doctor', 'Почетный доктор')], default='no', max_length=50, verbose_name='Статус'),
        ),
    ]
