# Generated by Django 4.0.3 on 2022-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_detailmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
    ]
