# Generated by Django 4.0.3 on 2022-05-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_positionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='position',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='faculty.positionmodel', verbose_name='Должность'),
        ),
    ]
