# Generated by Django 4.0.3 on 2022-05-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_teachermodel_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionmodel',
            options={'ordering': ['level'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RenameField(
            model_name='positionmodel',
            old_name='position_level',
            new_name='level',
        ),
    ]
