# Generated by Django 4.0.3 on 2022-04-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_remove_detailmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='eduform',
            field=models.ManyToManyField(related_name='edu_form', to='faculty.eduformmodel', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='eduformmodel',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.detailmodel', verbose_name='Иконка'),
        ),
    ]
