# Generated by Django 4.0.3 on 2022-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_educationmodel_eduform_eduformmodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduformmodel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
