# Generated by Django 4.0.3 on 2022-05-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_positionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'ordering': ('position',), 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
