# Generated by Django 4.0.3 on 2022-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_eduformmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='info',
            field=models.ManyToManyField(related_name='info', to='faculty.eduformmodel', verbose_name='Общая информация'),
        ),
    ]
