# Generated by Django 4.0.3 on 2022-05-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_teachermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmodel',
            name='page',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='faculty.pagesmodel', verbose_name='Страница'),
        ),
    ]
