# Generated by Django 4.0.3 on 2022-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_educationmodel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='info',
            field=models.ManyToManyField(related_name='info', to='faculty.detailmodel', verbose_name='Общая информация'),
        ),
    ]
