# Generated by Django 4.0.3 on 2022-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_educationmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmodel',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='detail_document', to='faculty.documentmodel', verbose_name='Документы'),
        ),
    ]
