# Generated by Django 4.0.3 on 2022-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_detailmodel_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='documents',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='education_document', to='faculty.documentmodel', verbose_name='Документы'),
        ),
    ]
