# Generated by Django 4.0.3 on 2022-04-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_profilemodel_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymodel',
            options={'ordering': ('id',), 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
    ]
