# Generated by Django 4.0.3 on 2022-04-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_alter_facultymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ('key',), 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='key',
            field=models.BigIntegerField(default=1),
        ),
    ]
