# Generated by Django 4.0.3 on 2022-05-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_alter_profilemodel_options_profilemodel_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduformmodel',
            options={'ordering': ('pk',), 'verbose_name': 'Форма обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='curriculum_vitae',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Curriculum Vitae'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='facebook',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='telegram',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='faculty.coursemodel', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='detail_profile', to='faculty.detailmodel', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='faculty.documentmodel', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='edu_form',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eduform', to='faculty.eduformmodel', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='education',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='faculty.educationmodel', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='faculty.facultymodel', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='key',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='professions', to='faculty.professionmodel', verbose_name='Професии'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='faculty.skillmodel', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='faculty.teachermodel', verbose_name='Преподаватели'),
        ),
    ]
