# Generated by Django 4.0.3 on 2022-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_alter_eduformmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='instagram',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='youtube',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='YouTube'),
        ),
    ]
