# Generated by Django 4.0.3 on 2022-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_teachermodel_instagram_teachermodel_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='status',
            field=models.CharField(choices=[('1', 'Преподаватель'), ('2', 'Старший преподаватель'), ('3', 'Кандитат наук'), ('4', 'Профессор'), ('5', 'Доцент')], default='1', max_length=20, verbose_name='Звание'),
        ),
    ]
