# Generated by Django 4.0.3 on 2022-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_teachermodel_slug_teachermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='teachers',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_query_name='education', to='faculty.teachermodel', verbose_name='Преподаватели'),
        ),
    ]
