# Generated by Django 4.0.3 on 2022-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_remove_profilemodel_teachers_educationmodel_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='telegram',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)Номер тефона с кодом страны', verbose_name='Телеграм'),
        ),
    ]
