# Generated by Django 4.0.3 on 2022-05-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_alter_teachermodel_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='youtube',
        ),
    ]
