# Generated by Django 4.0.3 on 2022-05-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0023_remove_teachermodel_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='curriculum_vitae',
        ),
    ]
