# Generated by Django 4.0.3 on 2022-05-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_remove_teachermodel_curriculum_vitae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='description',
        ),
    ]
