# Generated by Django 4.0.3 on 2022-05-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0025_remove_teachermodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='status',
        ),
    ]
