# Generated by Django 4.0.3 on 2022-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0026_remove_teachermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='curriculum_vitae',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Curriculum Vitae'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='facebook',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='image',
            field=models.FileField(blank=True, upload_to='faculty/images/teachers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='instagram',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='status',
            field=models.CharField(choices=[('1', 'Преподаватель'), ('2', 'Старший преподаватель'), ('3', 'Кандитат наук'), ('4', 'Профессор'), ('5', 'Доцент')], default='1', max_length=20, verbose_name='Звание'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='telegram',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='youtube',
            field=models.SlugField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', verbose_name='YouTube'),
        ),
    ]
