# Generated by Django 4.0.3 on 2022-05-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_teachermodel_curriculum_vitae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='edu_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eduform', to='faculty.eduformmodel', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='faculty.educationmodel', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='faculty.facultymodel', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='curriculum_vitae',
            field=models.FileField(blank=True, upload_to='faculty/files/cv', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='facebook',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='instagram',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='telegram',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='youtube',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='YouTube'),
        ),
    ]
