# Generated by Django 4.0.3 on 2022-05-24 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='news/files/posts/%y/%m/%d', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.FileField(blank=True, null=True, upload_to='news/images/posts/%y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'активен'), ('passive', 'не активен')], default='passive', max_length=15, verbose_name='Статус')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(unique_for_date='date', verbose_name='Ссылка')),
                ('banner', models.FileField(blank=True, upload_to='news/images/banners', verbose_name='Баннер')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Текст')),
                ('categories', models.ManyToManyField(related_name='categories', related_query_name='posts', to='news.categorymodel', verbose_name='Категории')),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='files', to='news.filemodel', verbose_name='Файлы')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='images', to='news.imagemodel', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-date',),
            },
        ),
    ]
