# Generated by Django 4.0.3 on 2022-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_categorymodel_options_alter_filemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='files', to='news.filemodel', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='news.imagemodel', verbose_name='Фотографии'),
        ),
    ]
