# Generated by Django 4.0.3 on 2022-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_categorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(verbose_name='Ссылка'),
        ),
    ]
