# Generated by Django 4.0.3 on 2022-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_categorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='categories',
            field=models.ManyToManyField(related_name='categories', related_query_name='posts', to='news.categorymodel', verbose_name='Категории'),
        ),
    ]
