# Generated by Django 4.0.3 on 2022-04-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_postmodel_banner_alter_filemodel_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
